source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.3'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

def shared
  config = use_native_modules!

  use_react_native!(path: config['reactNativePath'])
end

target 'FoodJob' do
  shared

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.79.0' })
end

post_install do |installer|
  flipper_post_install(installer)
end
